---
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  become: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['aws'] }}"

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['aws'] }}"

- name: Set root password and remove anonymous users
  mysql_user:
    login_user: root
    login_password: ''
    name: root
    host_all: yes
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    state: present
  become: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['aws'] }}"

- name: Create application database
  mysql_db:
    name: "{{ mysql_database }}"
    state: present
  become: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['aws'] }}"

- name: Create application user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    state: present
  become: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['aws'] }}"
